name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: macos-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Build
      run: yarn

    - name: Test
      run: yarn test
